name:                bosh-yaml-hs
version:             0.1.0.0
github:              "akshaymankar/bosh-yaml-hs"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/bosh-yaml-hs#readme>

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- bytestring
- hashable
- scientific
- text
- unordered-containers
- vector
- yaml

library:
  source-dirs: src

executables:
  bosh-yaml:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bosh-yaml-hs

tests:
  bosh-yaml-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bosh-yaml-hs
    - hspec
    - hspec-attoparsec
